@echo off
REM ============================================
REM SDS BareMetal Configuration - AutoHotKey Runner
REM Generated by Ansible - DO NOT EDIT MANUALLY
REM Total Servers: 1
REM ============================================

setlocal EnableDelayedExpansion

REM Configuration
set "AHK_EXE=C:\Users\Administrator\Desktop\AnsibleMediakit\SDS_BareMetal\AutoHotkeyU64.exe"
set "SCRIPT_DIR=C:\Users\Administrator\Desktop\AnsibleMediakit\SDS_BareMetal"
set "WAIT_BETWEEN_NODES=10"
set "WAIT_AFTER_PASSWORD=20"
set "WAIT_AFTER_SETTINGS=25"

echo ============================================
echo SDS BareMetal Configuration Automation
echo Total Servers to Configure: 1
echo ============================================
echo.
echo IMPORTANT: Do NOT move the mouse or press any keys during execution!
echo.
echo Press any key to start configuration...
pause >nul

REM Kill any existing AutoHotKey instances
echo.
echo Killing any existing AutoHotKey processes...
taskkill /F /IM AutoHotkeyU64.exe >nul 2>&1

echo.
echo ============================================
echo Configuring Node 1: sds-node1
echo iLO Host: 172.23.55.100
echo ============================================

REM Step 1: Setup Password for Node 1
echo [1/1] Step 1: Setting up password for sds-node1...
"%AHK_EXE%" "%SCRIPT_DIR%\setup_password_1.ahk"
timeout /t %WAIT_AFTER_PASSWORD% /nobreak >nul

REM Kill AutoHotKey after password setup
taskkill /F /IM AutoHotkeyU64.exe >nul 2>&1
timeout /t 5 /nobreak >nul

REM Step 2: Configure Settings for Node 1
echo [1/1] Step 2: Configuring settings for sds-node1...
"%AHK_EXE%" "%SCRIPT_DIR%\set_setting_1.ahk"
timeout /t %WAIT_AFTER_SETTINGS% /nobreak >nul

REM Kill AutoHotKey after settings
taskkill /F /IM AutoHotkeyU64.exe >nul 2>&1

echo [1/1] Completed configuration for sds-node1


echo.
echo ============================================
echo All 1 nodes configured successfully!
echo ============================================
echo.
pause
