; AutoHotKey Script: Set Settings for SDS Node
; Generated by Ansible - DO NOT EDIT MANUALLY
; INI File: C:\Users\Administrator\Desktop\AnsibleMediakit\SDS_BareMetal\SN1.ini

#SingleInstance Force
SetTitleMatchMode, 2

; [INI-file] Read variables
IniRead, ilo_host, C:\Users\Administrator\Desktop\AnsibleMediakit\SDS_BareMetal\SN1.ini, ilo, host
IniRead, ilo_user, C:\Users\Administrator\Desktop\AnsibleMediakit\SDS_BareMetal\SN1.ini, ilo, user
IniRead, ilo_pw, C:\Users\Administrator\Desktop\AnsibleMediakit\SDS_BareMetal\SN1.ini, ilo, pw
IniRead, setup_pw, C:\Users\Administrator\Desktop\AnsibleMediakit\SDS_BareMetal\SN1.ini, node, setup_pw
IniRead, hostname, C:\Users\Administrator\Desktop\AnsibleMediakit\SDS_BareMetal\SN1.ini, node, hostname
IniRead, ipv4address, C:\Users\Administrator\Desktop\AnsibleMediakit\SDS_BareMetal\SN1.ini, controlnw, ipv4address
IniRead, subnetmask, C:\Users\Administrator\Desktop\AnsibleMediakit\SDS_BareMetal\SN1.ini, controlnw, subnetmask
IniRead, mtu, C:\Users\Administrator\Desktop\AnsibleMediakit\SDS_BareMetal\SN1.ini, controlnw, mtu
IniRead, route_count, C:\Users\Administrator\Desktop\AnsibleMediakit\SDS_BareMetal\SN1.ini, controlnw, route_count
IniRead, route_destination1, C:\Users\Administrator\Desktop\AnsibleMediakit\SDS_BareMetal\SN1.ini, controlnw, route_destination1
IniRead, route_gateway1, C:\Users\Administrator\Desktop\AnsibleMediakit\SDS_BareMetal\SN1.ini, controlnw, route_gateway1

; irc_open - Open iLO Remote Console
Run "C:\Program Files\Google\Chrome\Application\chrome.exe" "-new-window" "https://%ilo_host%/irc/login"
Sleep 15000

; Wait for Chrome window with iLO
WinWait, iLO
WinActivate, iLO
Sleep 3000

; Navigate to username field using Tab
Send {Tab}{Tab}{Tab}
Sleep 500

; Clear any existing content and enter username
Send ^a
Send %ilo_user%
Sleep 500

; Tab to password field
Send {Tab}
Sleep 500

; Enter password and submit
Send %ilo_pw%
Sleep 500
Send {Enter}
Sleep 15000

; [Console] Log in
Send, {Down}
Send, {Enter}
Sleep, 5000

; [Console] Password
Send, %setup_pw%{Enter}
Sleep, 5000

; [Console] Set setting
Send, {Enter}
Sleep, 5000

; [Console] Storage node name
Send, {Enter}
Sleep, 5000
Send, %hostname%{Enter}
Sleep, 5000
Send, {Down 2}
Send, {Enter}
Sleep, 5000
Send, {Enter}
Sleep, 5000

; [Console] IP address
Send, {Enter}
Sleep, 5000
Send, %ipv4address%
Sleep, 5000
Send, {Down 2}
Sleep, 5000

; [Console] Subnet mask
Send, {Enter}
Sleep, 5000
Send, %subnetmask%{Enter}
Sleep, 5000

; [Console] MTU
Send, {Down}
Send, {Enter}
Sleep, 5000
Send, %mtu%{Enter}
Sleep, 5000

; [Console] Routing table
Send, {Down 2}
Send, {Enter}
Sleep, 5000
Send, %route_count%{Enter}
Sleep, 5000

; [Console] OK
Send, {Down 3}
Send, {Enter}
Sleep, 5000

; [Console] Route - Destination
Send, {Enter}
Sleep, 5000
Send, %route_destination1%{Enter}
Sleep, 5000

; [Console] Gateway
Send, {Down}
Send, {Enter}
Sleep, 5000
Send, %route_gateway1%{Enter}
Sleep, 5000

; [Console] OK
Send, {Down 3}
Send, {Enter}
Sleep, 5000

; [Console] Next
Send, {Enter}
Sleep, 5000

; [Console] Submit
Send, {Enter}
Sleep, 5000

; [Console] OK
Send, {Down}
Send, {Enter}
Sleep, 15000

; [iLO] Close iLO remote console
WinClose iLO
Exit
