; AutoHotKey Script: Setup Password for SDS Node
; Generated by Ansible - DO NOT EDIT MANUALLY
; INI File: C:\Users\Administrator\Desktop\AnsibleMediakit\SDS_BareMetal\SN1.ini

#SingleInstance Force
SetTitleMatchMode, 2

; [Conf] Default password
setup_default_pw := "hsds-setup"

; [INI-file] Read variables
IniRead, host, C:\Users\Administrator\Desktop\AnsibleMediakit\SDS_BareMetal\SN1.ini, ilo, host
IniRead, user, C:\Users\Administrator\Desktop\AnsibleMediakit\SDS_BareMetal\SN1.ini, ilo, user
IniRead, pw, C:\Users\Administrator\Desktop\AnsibleMediakit\SDS_BareMetal\SN1.ini, ilo, pw
IniRead, setup_pw, C:\Users\Administrator\Desktop\AnsibleMediakit\SDS_BareMetal\SN1.ini, node, setup_pw

; irc_open - Open iLO Remote Console
Run "C:\Program Files\Google\Chrome\Application\chrome.exe" "-new-window" "https://%host%/irc/login"
Sleep 15000

; Wait for Chrome window with iLO
WinWait, iLO
WinActivate, iLO
Sleep 3000

; Click on the username field area (right side of page where login form is)
; First Tab to ensure we start from a known position, then navigate to username field
Send {Tab}{Tab}{Tab}
Sleep 500

; Clear any existing content and enter username
Send ^a
Send %user%
Sleep 500

; Tab to password field
Send {Tab}
Sleep 500

; Enter password and submit
Send %pw%
Sleep 500
Send {Enter}
Sleep 15000

; [Console] Log in
Send, {Down}
Send, {Enter}
Sleep, 5000

; [Console] Password - Enter default password
Send, %setup_default_pw%{Enter}
Sleep, 5000

; [Console] Current password
Send, %setup_default_pw%{Enter}
Sleep, 5000

; [Console] New password
Send, %setup_pw%{Enter}
Sleep, 5000

; [Console] Retype new password
Send, %setup_pw%{Enter}
Sleep, 5000

; [Console] Logout
Send, {Down 6}
Send, {Enter}
Sleep, 5000

; [iLO] Close iLO remote console
WinClose iLO
Exit
