
---
namespace: hitachivantara
name: toolkit
version: 1.1.1
readme: README.md
authors:
  - Hitachi Vantara Ansible Toolkit Team
description: >
  Ansible Modules to manage SMCI servers, and switch to support HIS solutions.
license:
  - GPL-3.0-or-later
tags:
  - hitachi
  - hv
  - hitachi_vantara
dependencies: {}
repository: https://gpse-git.hitachivantara.com/scm/ipse/toolkit-ansible.git
documentation: NA
issues: NA
build_ignore:
  - tests/integration/ # Example: Ignore integration tests
  - .git
  - collection_build.sh
  - .pylintrc
  - .gitignore
  - Dockerfile
  - pylint_run_report.txt
  - .rabi
  - plugins/module_utils/unit_test
  - scripts
  - .vscode
  - spec
  - version.txt
  - lambda_package
  - run_linter.py
  - lint_report.txt
  - sanity_test_report.txt
  - file_name_wo_ext_cwd.sh
  - test_ansible_doc.sh
  - ansible.cfg
