---
- name: Ucptoolkit for HA Nodes - Interactive Menu System
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    ha_menu_options:
      "1": "ucp_all(Default) - This applies BIOS template, boot SPV, and boot ESXi installer"
      "2": "ucp_BIOS_load - This applies BIOS template"
      "3": "ucp_BIOS_save - This exports BIOS setting to a file"
      "4": "ucp_firmware - This applies iLo, System ROM, or Server Platform Service firmware"
      "5": "ucp_mount_reboot - This mounts the selected ISO file and boot from it"
      "6": "ucp_power_off"
      "7": "ucp_power_on"
      "8": "ucp_user_creation"
      "9": "Azure_Stack_HCI"
      "10": "Setup_VSSB_Servers"
      "11": "Exit"
    log_directory: "{{ ansible_env.PWD }}/logs"
    current_timestamp: "{{ ansible_date_time.year }}_{{ ansible_date_time.month }}_{{ ansible_date_time.day }}_{{ ansible_date_time.hour }}_{{ ansible_date_time.minute }}_{{ ansible_date_time.second }}"
    log_file: "{{ log_directory }}/Ucptoolkit_HA{{ current_timestamp }}.log"
    
  tasks:
    - name: Display welcome screen
      debug:
        msg: |
          
          Welcome to Ucptoolkit for HA Nodes!!!
          
          Please select the appropriate option from the menu below as per your requirement...
          {% for key, value in ha_menu_options.items() %}
          {{ key }}: {{ value }}
          {% endfor %}

    - name: Create logs directory if it doesn't exist
      file:
        path: "{{ log_directory }}"
        state: directory
        mode: '0755'

    - name: Prompt user for menu selection
      pause:
        prompt: |
          
          Please select your option now (1-11)
      register: user_selection

    - name: Validate user selection
      fail:
        msg: "Invalid option selected. Please enter a number between 1 and 11."
      when: user_selection.user_input not in ha_menu_options.keys()

    - name: Display selected option
      debug:
        msg: "Perfect! You have selected option {{ user_selection.user_input }}: {{ ha_menu_options[user_selection.user_input] }}"

    - name: Log operation start
      lineinfile:
        path: "{{ log_file }}"
        line: "{{ ansible_date_time.iso8601 }} - INFO - Starting operation: {{ ha_menu_options[user_selection.user_input] }}"
        create: yes

    # Call appropriate module based on selection
    - name: Execute UCP All (Default)
      include_tasks: tasks/ucp_all_tasks.yml
      when: user_selection.user_input in ["1", "9", "10"]

    - name: Execute BIOS Load
      include_tasks: tasks/ucp_bios_load_tasks.yml
      when: user_selection.user_input == "2"

    - name: Execute BIOS Save
      include_tasks: tasks/ucp_bios_save_tasks.yml
      when: user_selection.user_input == "3"

    - name: Execute Firmware Update
      include_tasks: tasks/ucp_firmware_tasks.yml
      when: user_selection.user_input == "4"

    - name: Execute Mount and Reboot
      include_tasks: tasks/ucp_mount_reboot_tasks.yml
      when: user_selection.user_input == "5"

    - name: Execute Power Off
      include_tasks: tasks/ucp_power_off_tasks.yml
      when: user_selection.user_input == "6"

    - name: Execute Power On
      include_tasks: tasks/ucp_power_on_tasks.yml
      when: user_selection.user_input == "7"

    - name: Execute User Creation
      include_tasks: tasks/ucp_user_creation_tasks.yml
      when: user_selection.user_input == "8"

    - name: Exit playbook
      debug:
        msg: "Exiting Ucptoolkit HA. Goodbye!"
      when: user_selection.user_input == "11"

    - name: End playbook execution on exit
      meta: end_play
      when: user_selection.user_input == "11"

    - name: Log operation completion
      lineinfile:
        path: "{{ log_file }}"
        line: "{{ ansible_date_time.iso8601 }} - INFO - Completed operation: {{ ha_menu_options[user_selection.user_input] }}"